import "./globals.css";

import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

// @lib
import { cn } from "@/lib/utils";

// @components
import {
  ModalProvider,
  ReduxProvider,
  SocketProvider,
  ThemeProvider,
  QueryProvider,
} from "@/components/providers/index";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            storageKey="discord-theme"
          >
            <QueryProvider>
              <SocketProvider>
                <ReduxProvider>
                  <ModalProvider />
                  {children}
                </ReduxProvider>
              </SocketProvider>
            </QueryProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
